### PR TITLE
fix(lib): use `.form` instead of `.query` when relevant and added `Accept: application/json` header

### LINKED ISSUE #128: bug: text sent by url instead of form encoding
### Description

The text is sent by url encoding the text instead of sending it in the body and with the header `content-type: application/x-www-form-urlencoded`. The languagetool api only supports it by sending it with the body and the header content-type set properly

### Part

Library (crate)

### Version

main

### Platform

macOS

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by okaerin**
Closes #128

# Description
Change to use the `form` method instead of `query`

## Check List (Check all the applicable boxes)

- [x] I understand that my contributions needs to pass the checks.
- [x] If I created new functions / methods, I documented them and add type hints.
- [x] If I modified already existing code, I updated the documentation accordingly.
- [x] The title of my pull request is a short description of the requested changes.

# Screenshots

### CODE REVIEW

File: src/lib/server.rs [hunk 1]
```diff
@@ -485,7 +486,8 @@ impl ServerClient {
         match self
             .client
             .get(format!("{}/words", self.api))
-            .query(request)
+            .header(ACCEPT, HeaderValue::from_static("application/json"))
+            .form(request)
             .send()
```
Comment (ccoVeille) [inline src/lib/server.rs:491]: Unlike others, this endpoint is using GET and accepts parameters.

So it would be a strange API design to use GET + form (so send application/x-www-form-urlencoded)

It is confirmed by the openapi spec

https://languagetool.org/http-api/#/default

https://languagetool.org/http-api/languagetool-swagger.json



GET /words is the only one to use query 

So I think this shouldn't be changed. Or at least it should be triple-check. If the server supports it or not.

So I wouldn't change GET /words except the accept header.

File: src/lib/server.rs [hunk 2]
```diff
@@ -485,7 +486,8 @@ impl ServerClient {
         match self
             .client
             .get(format!("{}/words", self.api))
-            .query(request)
+            .header(ACCEPT, HeaderValue::from_static("application/json"))
+            .form(request)
```
Comment (jeertmans) [inline src/lib/server.rs:490]:
```suggestion
            .query(request)
```

File: src/lib/server.rs (hunk 1 above)
Comment (jeertmans) [reply src/lib/server.rs:491]: Hi @ccoVeille, thanks for your valuable comment! I confirm that this is also what I suppose: this should be the only `query` request, others use `formData`.

**Review by jeertmans — CHANGES_REQUESTED** [review]
Hi @okaerin, thanks for your PR!

In my opinion, it looks great! I only made one suggestion, see the comment from @ccoVeille.

Other than that, could you please edit the `CHANGELOG.md` file to include a section about this fix?

File: src/lib/server.rs (hunk 1 above)
Comment (jeertmans) [reply src/lib/server.rs]: No worries, thanks :-)

**Comment by jeertmans** [comment]
Looks great, thanks @okaerin!

**Review by jeertmans — APPROVED** [review]
